package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * Barcode generated by hbm2java
 */
public class Barcode implements java.io.Serializable {

	private Serializable barcode;
	private Products products;
	private int branchId;
	private Timestamp dateAdd;

	public Barcode() {
	}

	public Barcode(Serializable barcode, Products products, int branchId, Timestamp dateAdd) {
		this.barcode = barcode;
		this.products = products;
		this.branchId = branchId;
		this.dateAdd = dateAdd;
	}

	public Serializable getBarcode() {
		return this.barcode;
	}

	public void setBarcode(Serializable barcode) {
		this.barcode = barcode;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public Timestamp getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Timestamp dateAdd) {
		this.dateAdd = dateAdd;
	}

}
