package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch implements java.io.Serializable {

	private Integer idBranch;
	private Serializable name;
	private Serializable fullName;
	private Set productses = new HashSet(0);

	public Branch() {
	}

	public Branch(Serializable name, Serializable fullName, Set productses) {
		this.name = name;
		this.fullName = fullName;
		this.productses = productses;
	}

	public Integer getIdBranch() {
		return this.idBranch;
	}

	public void setIdBranch(Integer idBranch) {
		this.idBranch = idBranch;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getFullName() {
		return this.fullName;
	}

	public void setFullName(Serializable fullName) {
		this.fullName = fullName;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
