package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Currency generated by hbm2java
 */
public class Currency implements java.io.Serializable {

	private Integer idCurrency;
	private Serializable name;
	private Serializable fullName;
	private Set incomeses = new HashSet(0);
	private Set wayBillses = new HashSet(0);
	private Set invoiceses = new HashSet(0);

	public Currency() {
	}

	public Currency(Serializable name, Serializable fullName, Set incomeses, Set wayBillses, Set invoiceses) {
		this.name = name;
		this.fullName = fullName;
		this.incomeses = incomeses;
		this.wayBillses = wayBillses;
		this.invoiceses = invoiceses;
	}

	public Integer getIdCurrency() {
		return this.idCurrency;
	}

	public void setIdCurrency(Integer idCurrency) {
		this.idCurrency = idCurrency;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getFullName() {
		return this.fullName;
	}

	public void setFullName(Serializable fullName) {
		this.fullName = fullName;
	}

	public Set getIncomeses() {
		return this.incomeses;
	}

	public void setIncomeses(Set incomeses) {
		this.incomeses = incomeses;
	}

	public Set getWayBillses() {
		return this.wayBillses;
	}

	public void setWayBillses(Set wayBillses) {
		this.wayBillses = wayBillses;
	}

	public Set getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set invoiceses) {
		this.invoiceses = invoiceses;
	}

}
