package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers implements java.io.Serializable {

	private Integer custId;
	private CustContract custContract;
	private Country country;
	private Serializable name;
	private Serializable fullName;
	private Timestamp dateRegistration;
	private Serializable bank;
	private Serializable yhh;
	private Serializable bic;
	private Serializable adress;
	private Serializable adressTwo;
	private Serializable ownerFull;
	private Serializable ownerMini;
	private Serializable paymentAcc;
	private Serializable phone;
	private Boolean myFirm;
	private Set invoiceses = new HashSet(0);
	private Set wayBillses = new HashSet(0);
	private Set incomeses = new HashSet(0);
	private Set orders = new HashSet(0);

	public Customers() {
	}

	public Customers(CustContract custContract, Country country, Serializable name, Serializable fullName,
			Timestamp dateRegistration, Serializable bank, Serializable yhh, Serializable bic, Serializable adress,
			Serializable adressTwo, Serializable ownerFull, Serializable ownerMini, Serializable paymentAcc,
			Serializable phone, Boolean myFirm, Set invoiceses, Set wayBillses, Set incomeses, Set orders) {
		this.custContract = custContract;
		this.country = country;
		this.name = name;
		this.fullName = fullName;
		this.dateRegistration = dateRegistration;
		this.bank = bank;
		this.yhh = yhh;
		this.bic = bic;
		this.adress = adress;
		this.adressTwo = adressTwo;
		this.ownerFull = ownerFull;
		this.ownerMini = ownerMini;
		this.paymentAcc = paymentAcc;
		this.phone = phone;
		this.myFirm = myFirm;
		this.invoiceses = invoiceses;
		this.wayBillses = wayBillses;
		this.incomeses = incomeses;
		this.orders = orders;
	}

	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	public CustContract getCustContract() {
		return this.custContract;
	}

	public void setCustContract(CustContract custContract) {
		this.custContract = custContract;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getFullName() {
		return this.fullName;
	}

	public void setFullName(Serializable fullName) {
		this.fullName = fullName;
	}

	public Timestamp getDateRegistration() {
		return this.dateRegistration;
	}

	public void setDateRegistration(Timestamp dateRegistration) {
		this.dateRegistration = dateRegistration;
	}

	public Serializable getBank() {
		return this.bank;
	}

	public void setBank(Serializable bank) {
		this.bank = bank;
	}

	public Serializable getYhh() {
		return this.yhh;
	}

	public void setYhh(Serializable yhh) {
		this.yhh = yhh;
	}

	public Serializable getBic() {
		return this.bic;
	}

	public void setBic(Serializable bic) {
		this.bic = bic;
	}

	public Serializable getAdress() {
		return this.adress;
	}

	public void setAdress(Serializable adress) {
		this.adress = adress;
	}

	public Serializable getAdressTwo() {
		return this.adressTwo;
	}

	public void setAdressTwo(Serializable adressTwo) {
		this.adressTwo = adressTwo;
	}

	public Serializable getOwnerFull() {
		return this.ownerFull;
	}

	public void setOwnerFull(Serializable ownerFull) {
		this.ownerFull = ownerFull;
	}

	public Serializable getOwnerMini() {
		return this.ownerMini;
	}

	public void setOwnerMini(Serializable ownerMini) {
		this.ownerMini = ownerMini;
	}

	public Serializable getPaymentAcc() {
		return this.paymentAcc;
	}

	public void setPaymentAcc(Serializable paymentAcc) {
		this.paymentAcc = paymentAcc;
	}

	public Serializable getPhone() {
		return this.phone;
	}

	public void setPhone(Serializable phone) {
		this.phone = phone;
	}

	public Boolean getMyFirm() {
		return this.myFirm;
	}

	public void setMyFirm(Boolean myFirm) {
		this.myFirm = myFirm;
	}

	public Set getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set invoiceses) {
		this.invoiceses = invoiceses;
	}

	public Set getWayBillses() {
		return this.wayBillses;
	}

	public void setWayBillses(Set wayBillses) {
		this.wayBillses = wayBillses;
	}

	public Set getIncomeses() {
		return this.incomeses;
	}

	public void setIncomeses(Set incomeses) {
		this.incomeses = incomeses;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
