package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CustContract generated by hbm2java
 */
public class CustContract implements java.io.Serializable {

	private Integer idContract;
	private Serializable number;
	private Date firstDate;
	private Date endDate;
	private Set customerses = new HashSet(0);

	public CustContract() {
	}

	public CustContract(Serializable number, Date firstDate, Date endDate, Set customerses) {
		this.number = number;
		this.firstDate = firstDate;
		this.endDate = endDate;
		this.customerses = customerses;
	}

	public Integer getIdContract() {
		return this.idContract;
	}

	public void setIdContract(Integer idContract) {
		this.idContract = idContract;
	}

	public Serializable getNumber() {
		return this.number;
	}

	public void setNumber(Serializable number) {
		this.number = number;
	}

	public Date getFirstDate() {
		return this.firstDate;
	}

	public void setFirstDate(Date firstDate) {
		this.firstDate = firstDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Set getCustomerses() {
		return this.customerses;
	}

	public void setCustomerses(Set customerses) {
		this.customerses = customerses;
	}

}
