package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * GenreProduct generated by hbm2java
 */
public class GenreProduct implements java.io.Serializable {

	private Integer uid;
	private Genre genre;
	private int productId;

	public GenreProduct() {
	}

	public GenreProduct(Genre genre, int productId) {
		this.genre = genre;
		this.productId = productId;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Genre getGenre() {
		return this.genre;
	}

	public void setGenre(Genre genre) {
		this.genre = genre;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

}
