package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private Integer id;
	private Serializable language;

	public Language() {
	}

	public Language(Serializable language) {
		this.language = language;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Serializable getLanguage() {
		return this.language;
	}

	public void setLanguage(Serializable language) {
		this.language = language;
	}

}
