package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Measure generated by hbm2java
 */
public class Measure implements java.io.Serializable {

	private Integer id;
	private Serializable measureValue;
	private Set productses = new HashSet(0);

	public Measure() {
	}

	public Measure(Serializable measureValue, Set productses) {
		this.measureValue = measureValue;
		this.productses = productses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Serializable getMeasureValue() {
		return this.measureValue;
	}

	public void setMeasureValue(Serializable measureValue) {
		this.measureValue = measureValue;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
