package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

	private Integer uid;
	private Order order;
	private int branchId;
	private int productId;
	private Double qty;
	private Integer measure;

	public OrderDetails() {
	}

	public OrderDetails(Order order, int branchId, int productId, Double qty, Integer measure) {
		this.order = order;
		this.branchId = branchId;
		this.productId = productId;
		this.qty = qty;
		this.measure = measure;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Double getQty() {
		return this.qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	public Integer getMeasure() {
		return this.measure;
	}

	public void setMeasure(Integer measure) {
		this.measure = measure;
	}

}
