package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer uid;
	private Users users;
	private Status status;
	private Stores stores;
	private Customers customers;
	private Timestamp orderDate;
	private Serializable comments;
	private Timestamp readyDate;
	private Boolean ready;
	private Set orderDetailses = new HashSet(0);

	public Order() {
	}

	public Order(Users users, Status status, Stores stores, Customers customers, Timestamp orderDate,
			Serializable comments, Timestamp readyDate, Boolean ready, Set orderDetailses) {
		this.users = users;
		this.status = status;
		this.stores = stores;
		this.customers = customers;
		this.orderDate = orderDate;
		this.comments = comments;
		this.readyDate = readyDate;
		this.ready = ready;
		this.orderDetailses = orderDetailses;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public Stores getStores() {
		return this.stores;
	}

	public void setStores(Stores stores) {
		this.stores = stores;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public Timestamp getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Timestamp orderDate) {
		this.orderDate = orderDate;
	}

	public Serializable getComments() {
		return this.comments;
	}

	public void setComments(Serializable comments) {
		this.comments = comments;
	}

	public Timestamp getReadyDate() {
		return this.readyDate;
	}

	public void setReadyDate(Timestamp readyDate) {
		this.readyDate = readyDate;
	}

	public Boolean getReady() {
		return this.ready;
	}

	public void setReady(Boolean ready) {
		this.ready = ready;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
