package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PriceCategories generated by hbm2java
 */
public class PriceCategories implements java.io.Serializable {

	private Integer uid;
	private Serializable name;
	private Set invoiceses = new HashSet(0);
	private Set wayBillses = new HashSet(0);

	public PriceCategories() {
	}

	public PriceCategories(Serializable name, Set invoiceses, Set wayBillses) {
		this.name = name;
		this.invoiceses = invoiceses;
		this.wayBillses = wayBillses;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Set getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set invoiceses) {
		this.invoiceses = invoiceses;
	}

	public Set getWayBillses() {
		return this.wayBillses;
	}

	public void setWayBillses(Set wayBillses) {
		this.wayBillses = wayBillses;
	}

}
