package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private Integer productId;
	private Measure measure;
	private Sertificate sertificate;
	private Country country;
	private Branch branch;
	private Serializable name;
	private Integer qty;
	private Serializable description;
	private Set barcodes = new HashSet(0);

	public Products() {
	}

	public Products(Measure measure, Sertificate sertificate, Country country, Branch branch, Serializable name,
			Integer qty, Serializable description, Set barcodes) {
		this.measure = measure;
		this.sertificate = sertificate;
		this.country = country;
		this.branch = branch;
		this.name = name;
		this.qty = qty;
		this.description = description;
		this.barcodes = barcodes;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public Measure getMeasure() {
		return this.measure;
	}

	public void setMeasure(Measure measure) {
		this.measure = measure;
	}

	public Sertificate getSertificate() {
		return this.sertificate;
	}

	public void setSertificate(Sertificate sertificate) {
		this.sertificate = sertificate;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public Set getBarcodes() {
		return this.barcodes;
	}

	public void setBarcodes(Set barcodes) {
		this.barcodes = barcodes;
	}

}
