package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Sertificate generated by hbm2java
 */
public class Sertificate implements java.io.Serializable {

	private Integer idSert;
	private int branchId;
	private int productId;
	private Serializable numSert;
	private Date dateEnd;
	private Timestamp dateAdd;
	private Set productses = new HashSet(0);

	public Sertificate() {
	}

	public Sertificate(int branchId, int productId, Serializable numSert, Date dateEnd, Timestamp dateAdd,
			Set productses) {
		this.branchId = branchId;
		this.productId = productId;
		this.numSert = numSert;
		this.dateEnd = dateEnd;
		this.dateAdd = dateAdd;
		this.productses = productses;
	}

	public Integer getIdSert() {
		return this.idSert;
	}

	public void setIdSert(Integer idSert) {
		this.idSert = idSert;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Serializable getNumSert() {
		return this.numSert;
	}

	public void setNumSert(Serializable numSert) {
		this.numSert = numSert;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	public Timestamp getDateAdd() {
		return this.dateAdd;
	}

	public void setDateAdd(Timestamp dateAdd) {
		this.dateAdd = dateAdd;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
