package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * Settings generated by hbm2java
 */
public class Settings implements java.io.Serializable {

	private Integer id;
	private Serializable option;
	private Serializable value;

	public Settings() {
	}

	public Settings(Serializable option, Serializable value) {
		this.option = option;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Serializable getOption() {
		return this.option;
	}

	public void setOption(Serializable option) {
		this.option = option;
	}

	public Serializable getValue() {
		return this.value;
	}

	public void setValue(Serializable value) {
		this.value = value;
	}

}
