package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status implements java.io.Serializable {

	private Integer statusId;
	private Serializable name;
	private boolean ord;
	private boolean inc;
	private boolean inv;
	private boolean wayB;
	private Set incomeses = new HashSet(0);
	private Set invoiceses = new HashSet(0);
	private Set orders = new HashSet(0);
	private Set wayBillses = new HashSet(0);

	public Status() {
	}

	public Status(Serializable name, boolean ord, boolean inc, boolean inv, boolean wayB, Set incomeses, Set invoiceses,
			Set orders, Set wayBillses) {
		this.name = name;
		this.ord = ord;
		this.inc = inc;
		this.inv = inv;
		this.wayB = wayB;
		this.incomeses = incomeses;
		this.invoiceses = invoiceses;
		this.orders = orders;
		this.wayBillses = wayBillses;
	}

	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public boolean isOrd() {
		return this.ord;
	}

	public void setOrd(boolean ord) {
		this.ord = ord;
	}

	public boolean isInc() {
		return this.inc;
	}

	public void setInc(boolean inc) {
		this.inc = inc;
	}

	public boolean isInv() {
		return this.inv;
	}

	public void setInv(boolean inv) {
		this.inv = inv;
	}

	public boolean isWayB() {
		return this.wayB;
	}

	public void setWayB(boolean wayB) {
		this.wayB = wayB;
	}

	public Set getIncomeses() {
		return this.incomeses;
	}

	public void setIncomeses(Set incomeses) {
		this.incomeses = incomeses;
	}

	public Set getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set invoiceses) {
		this.invoiceses = invoiceses;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

	public Set getWayBillses() {
		return this.wayBillses;
	}

	public void setWayBillses(Set wayBillses) {
		this.wayBillses = wayBillses;
	}

}
