package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stock generated by hbm2java
 */
public class Stock implements java.io.Serializable {

	private Integer idStock;
	private Serializable name;
	private Date firstDate;
	private Date dateEnd;
	private Integer stores;
	private Set wayBillses = new HashSet(0);
	private Set invoiceses = new HashSet(0);
	private Set incomeses = new HashSet(0);

	public Stock() {
	}

	public Stock(Serializable name, Date firstDate, Date dateEnd, Integer stores, Set wayBillses, Set invoiceses,
			Set incomeses) {
		this.name = name;
		this.firstDate = firstDate;
		this.dateEnd = dateEnd;
		this.stores = stores;
		this.wayBillses = wayBillses;
		this.invoiceses = invoiceses;
		this.incomeses = incomeses;
	}

	public Integer getIdStock() {
		return this.idStock;
	}

	public void setIdStock(Integer idStock) {
		this.idStock = idStock;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Date getFirstDate() {
		return this.firstDate;
	}

	public void setFirstDate(Date firstDate) {
		this.firstDate = firstDate;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	public Integer getStores() {
		return this.stores;
	}

	public void setStores(Integer stores) {
		this.stores = stores;
	}

	public Set getWayBillses() {
		return this.wayBillses;
	}

	public void setWayBillses(Set wayBillses) {
		this.wayBillses = wayBillses;
	}

	public Set getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set invoiceses) {
		this.invoiceses = invoiceses;
	}

	public Set getIncomeses() {
		return this.incomeses;
	}

	public void setIncomeses(Set incomeses) {
		this.incomeses = incomeses;
	}

}
