package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Stores generated by hbm2java
 */
public class Stores implements java.io.Serializable {

	private Integer uid;
	private Users users;
	private Serializable name;
	private Serializable adress;
	private Set invoiceses = new HashSet(0);
	private Set incomeses = new HashSet(0);
	private Set orders = new HashSet(0);
	private Set wayBillses = new HashSet(0);

	public Stores() {
	}

	public Stores(Users users, Serializable name, Serializable adress, Set invoiceses, Set incomeses, Set orders,
			Set wayBillses) {
		this.users = users;
		this.name = name;
		this.adress = adress;
		this.invoiceses = invoiceses;
		this.incomeses = incomeses;
		this.orders = orders;
		this.wayBillses = wayBillses;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getAdress() {
		return this.adress;
	}

	public void setAdress(Serializable adress) {
		this.adress = adress;
	}

	public Set getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set invoiceses) {
		this.invoiceses = invoiceses;
	}

	public Set getIncomeses() {
		return this.incomeses;
	}

	public void setIncomeses(Set incomeses) {
		this.incomeses = incomeses;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

	public Set getWayBillses() {
		return this.wayBillses;
	}

	public void setWayBillses(Set wayBillses) {
		this.wayBillses = wayBillses;
	}

}
