package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idUser;
	private UserPosition userPosition;
	private Serializable name;
	private Serializable lastName;
	private Serializable middleName;
	private Serializable fullName;
	private Serializable phoneNum;
	private Date dateBirth;
	private Timestamp dateFirstWork;
	private boolean isAdmin;
	private Serializable login;
	private Serializable password;
	private Serializable urlImages;
	private Set invoiceses = new HashSet(0);
	private Set incomeses = new HashSet(0);
	private Set storeses = new HashSet(0);
	private Set wayBillses = new HashSet(0);
	private Set orders = new HashSet(0);

	public Users() {
	}

	public Users(UserPosition userPosition, Serializable name, Serializable lastName, Serializable middleName,
			Serializable fullName, Serializable phoneNum, Date dateBirth, Timestamp dateFirstWork, boolean isAdmin,
			Serializable login, Serializable password, Serializable urlImages, Set invoiceses, Set incomeses,
			Set storeses, Set wayBillses, Set orders) {
		this.userPosition = userPosition;
		this.name = name;
		this.lastName = lastName;
		this.middleName = middleName;
		this.fullName = fullName;
		this.phoneNum = phoneNum;
		this.dateBirth = dateBirth;
		this.dateFirstWork = dateFirstWork;
		this.isAdmin = isAdmin;
		this.login = login;
		this.password = password;
		this.urlImages = urlImages;
		this.invoiceses = invoiceses;
		this.incomeses = incomeses;
		this.storeses = storeses;
		this.wayBillses = wayBillses;
		this.orders = orders;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public UserPosition getUserPosition() {
		return this.userPosition;
	}

	public void setUserPosition(UserPosition userPosition) {
		this.userPosition = userPosition;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	public Serializable getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(Serializable middleName) {
		this.middleName = middleName;
	}

	public Serializable getFullName() {
		return this.fullName;
	}

	public void setFullName(Serializable fullName) {
		this.fullName = fullName;
	}

	public Serializable getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(Serializable phoneNum) {
		this.phoneNum = phoneNum;
	}

	public Date getDateBirth() {
		return this.dateBirth;
	}

	public void setDateBirth(Date dateBirth) {
		this.dateBirth = dateBirth;
	}

	public Timestamp getDateFirstWork() {
		return this.dateFirstWork;
	}

	public void setDateFirstWork(Timestamp dateFirstWork) {
		this.dateFirstWork = dateFirstWork;
	}

	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	public Serializable getLogin() {
		return this.login;
	}

	public void setLogin(Serializable login) {
		this.login = login;
	}

	public Serializable getPassword() {
		return this.password;
	}

	public void setPassword(Serializable password) {
		this.password = password;
	}

	public Serializable getUrlImages() {
		return this.urlImages;
	}

	public void setUrlImages(Serializable urlImages) {
		this.urlImages = urlImages;
	}

	public Set getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set invoiceses) {
		this.invoiceses = invoiceses;
	}

	public Set getIncomeses() {
		return this.incomeses;
	}

	public void setIncomeses(Set incomeses) {
		this.incomeses = incomeses;
	}

	public Set getStoreses() {
		return this.storeses;
	}

	public void setStoreses(Set storeses) {
		this.storeses = storeses;
	}

	public Set getWayBillses() {
		return this.wayBillses;
	}

	public void setWayBillses(Set wayBillses) {
		this.wayBillses = wayBillses;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
