package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * UserPosition generated by hbm2java
 */
public class UserPosition implements java.io.Serializable {

	private Integer idPos;
	private Serializable name;
	private Serializable description;
	private Set userses = new HashSet(0);

	public UserPosition() {
	}

	public UserPosition(Serializable name, Serializable description, Set userses) {
		this.name = name;
		this.description = description;
		this.userses = userses;
	}

	public Integer getIdPos() {
		return this.idPos;
	}

	public void setIdPos(Integer idPos) {
		this.idPos = idPos;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
