package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * ViewCustomersId generated by hbm2java
 */
public class ViewCustomersId implements java.io.Serializable {

	private Serializable adress;
	private Serializable adressTwo;
	private Serializable bank;
	private Serializable bic;
	private Integer contract;
	private Integer country;
	private int custId;
	private Timestamp dateRegistration;
	private Date endDate;
	private Date firstDate;
	private Serializable fullName;
	private Boolean myFirm;
	private Serializable name;
	private Serializable number;
	private Serializable ownerFull;
	private Serializable ownerMini;
	private Serializable paymentAcc;
	private Serializable phone;
	private Serializable yhh;

	public ViewCustomersId() {
	}

	public ViewCustomersId(Serializable adress, Serializable adressTwo, Serializable bank, Serializable bic,
			Integer contract, Integer country, int custId, Timestamp dateRegistration, Date endDate, Date firstDate,
			Serializable fullName, Boolean myFirm, Serializable name, Serializable number, Serializable ownerFull,
			Serializable ownerMini, Serializable paymentAcc, Serializable phone, Serializable yhh) {
		this.adress = adress;
		this.adressTwo = adressTwo;
		this.bank = bank;
		this.bic = bic;
		this.contract = contract;
		this.country = country;
		this.custId = custId;
		this.dateRegistration = dateRegistration;
		this.endDate = endDate;
		this.firstDate = firstDate;
		this.fullName = fullName;
		this.myFirm = myFirm;
		this.name = name;
		this.number = number;
		this.ownerFull = ownerFull;
		this.ownerMini = ownerMini;
		this.paymentAcc = paymentAcc;
		this.phone = phone;
		this.yhh = yhh;
	}

	public Serializable getAdress() {
		return this.adress;
	}

	public void setAdress(Serializable adress) {
		this.adress = adress;
	}

	public Serializable getAdressTwo() {
		return this.adressTwo;
	}

	public void setAdressTwo(Serializable adressTwo) {
		this.adressTwo = adressTwo;
	}

	public Serializable getBank() {
		return this.bank;
	}

	public void setBank(Serializable bank) {
		this.bank = bank;
	}

	public Serializable getBic() {
		return this.bic;
	}

	public void setBic(Serializable bic) {
		this.bic = bic;
	}

	public Integer getContract() {
		return this.contract;
	}

	public void setContract(Integer contract) {
		this.contract = contract;
	}

	public Integer getCountry() {
		return this.country;
	}

	public void setCountry(Integer country) {
		this.country = country;
	}

	public int getCustId() {
		return this.custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	public Timestamp getDateRegistration() {
		return this.dateRegistration;
	}

	public void setDateRegistration(Timestamp dateRegistration) {
		this.dateRegistration = dateRegistration;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Date getFirstDate() {
		return this.firstDate;
	}

	public void setFirstDate(Date firstDate) {
		this.firstDate = firstDate;
	}

	public Serializable getFullName() {
		return this.fullName;
	}

	public void setFullName(Serializable fullName) {
		this.fullName = fullName;
	}

	public Boolean getMyFirm() {
		return this.myFirm;
	}

	public void setMyFirm(Boolean myFirm) {
		this.myFirm = myFirm;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getNumber() {
		return this.number;
	}

	public void setNumber(Serializable number) {
		this.number = number;
	}

	public Serializable getOwnerFull() {
		return this.ownerFull;
	}

	public void setOwnerFull(Serializable ownerFull) {
		this.ownerFull = ownerFull;
	}

	public Serializable getOwnerMini() {
		return this.ownerMini;
	}

	public void setOwnerMini(Serializable ownerMini) {
		this.ownerMini = ownerMini;
	}

	public Serializable getPaymentAcc() {
		return this.paymentAcc;
	}

	public void setPaymentAcc(Serializable paymentAcc) {
		this.paymentAcc = paymentAcc;
	}

	public Serializable getPhone() {
		return this.phone;
	}

	public void setPhone(Serializable phone) {
		this.phone = phone;
	}

	public Serializable getYhh() {
		return this.yhh;
	}

	public void setYhh(Serializable yhh) {
		this.yhh = yhh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewCustomersId))
			return false;
		ViewCustomersId castOther = (ViewCustomersId) other;

		return ((this.getAdress() == castOther.getAdress()) || (this.getAdress() != null
				&& castOther.getAdress() != null && this.getAdress().equals(castOther.getAdress())))
				&& ((this.getAdressTwo() == castOther.getAdressTwo()) || (this.getAdressTwo() != null
						&& castOther.getAdressTwo() != null && this.getAdressTwo().equals(castOther.getAdressTwo())))
				&& ((this.getBank() == castOther.getBank()) || (this.getBank() != null && castOther.getBank() != null
						&& this.getBank().equals(castOther.getBank())))
				&& ((this.getBic() == castOther.getBic()) || (this.getBic() != null && castOther.getBic() != null
						&& this.getBic().equals(castOther.getBic())))
				&& ((this.getContract() == castOther.getContract()) || (this.getContract() != null
						&& castOther.getContract() != null && this.getContract().equals(castOther.getContract())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& (this.getCustId() == castOther.getCustId())
				&& ((this.getDateRegistration() == castOther.getDateRegistration())
						|| (this.getDateRegistration() != null && castOther.getDateRegistration() != null
								&& this.getDateRegistration().equals(castOther.getDateRegistration())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this.getEndDate() != null
						&& castOther.getEndDate() != null && this.getEndDate().equals(castOther.getEndDate())))
				&& ((this.getFirstDate() == castOther.getFirstDate()) || (this.getFirstDate() != null
						&& castOther.getFirstDate() != null && this.getFirstDate().equals(castOther.getFirstDate())))
				&& ((this.getFullName() == castOther.getFullName()) || (this.getFullName() != null
						&& castOther.getFullName() != null && this.getFullName().equals(castOther.getFullName())))
				&& ((this.getMyFirm() == castOther.getMyFirm()) || (this.getMyFirm() != null
						&& castOther.getMyFirm() != null && this.getMyFirm().equals(castOther.getMyFirm())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getNumber() == castOther.getNumber()) || (this.getNumber() != null
						&& castOther.getNumber() != null && this.getNumber().equals(castOther.getNumber())))
				&& ((this.getOwnerFull() == castOther.getOwnerFull()) || (this.getOwnerFull() != null
						&& castOther.getOwnerFull() != null && this.getOwnerFull().equals(castOther.getOwnerFull())))
				&& ((this.getOwnerMini() == castOther.getOwnerMini()) || (this.getOwnerMini() != null
						&& castOther.getOwnerMini() != null && this.getOwnerMini().equals(castOther.getOwnerMini())))
				&& ((this.getPaymentAcc() == castOther.getPaymentAcc()) || (this.getPaymentAcc() != null
						&& castOther.getPaymentAcc() != null && this.getPaymentAcc().equals(castOther.getPaymentAcc())))
				&& ((this.getPhone() == castOther.getPhone()) || (this.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone().equals(castOther.getPhone())))
				&& ((this.getYhh() == castOther.getYhh()) || (this.getYhh() != null && castOther.getYhh() != null
						&& this.getYhh().equals(castOther.getYhh())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAdress() == null ? 0 : this.getAdress().hashCode());
		result = 37 * result + (getAdressTwo() == null ? 0 : this.getAdressTwo().hashCode());
		result = 37 * result + (getBank() == null ? 0 : this.getBank().hashCode());
		result = 37 * result + (getBic() == null ? 0 : this.getBic().hashCode());
		result = 37 * result + (getContract() == null ? 0 : this.getContract().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + this.getCustId();
		result = 37 * result + (getDateRegistration() == null ? 0 : this.getDateRegistration().hashCode());
		result = 37 * result + (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		result = 37 * result + (getFirstDate() == null ? 0 : this.getFirstDate().hashCode());
		result = 37 * result + (getFullName() == null ? 0 : this.getFullName().hashCode());
		result = 37 * result + (getMyFirm() == null ? 0 : this.getMyFirm().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getNumber() == null ? 0 : this.getNumber().hashCode());
		result = 37 * result + (getOwnerFull() == null ? 0 : this.getOwnerFull().hashCode());
		result = 37 * result + (getOwnerMini() == null ? 0 : this.getOwnerMini().hashCode());
		result = 37 * result + (getPaymentAcc() == null ? 0 : this.getPaymentAcc().hashCode());
		result = 37 * result + (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (getYhh() == null ? 0 : this.getYhh().hashCode());
		return result;
	}

}
