package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewOrderDetails generated by hbm2java
 */
public class ViewOrderDetails implements java.io.Serializable {

	private ViewOrderDetailsId id;

	public ViewOrderDetails() {
	}

	public ViewOrderDetails(ViewOrderDetailsId id) {
		this.id = id;
	}

	public ViewOrderDetailsId getId() {
		return this.id;
	}

	public void setId(ViewOrderDetailsId id) {
		this.id = id;
	}

}
