package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewIncomeDetails generated by hbm2java
 */
public class ViewIncomeDetails implements java.io.Serializable {

	private ViewIncomeDetailsId id;

	public ViewIncomeDetails() {
	}

	public ViewIncomeDetails(ViewIncomeDetailsId id) {
		this.id = id;
	}

	public ViewIncomeDetailsId getId() {
		return this.id;
	}

	public void setId(ViewIncomeDetailsId id) {
		this.id = id;
	}

}
