package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewSale generated by hbm2java
 */
public class ViewSale implements java.io.Serializable {

	private ViewSaleId id;

	public ViewSale() {
	}

	public ViewSale(ViewSaleId id) {
		this.id = id;
	}

	public ViewSaleId getId() {
		return this.id;
	}

	public void setId(ViewSaleId id) {
		this.id = id;
	}

}
