package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewIncomes generated by hbm2java
 */
public class ViewIncomes implements java.io.Serializable {

	private ViewIncomesId id;

	public ViewIncomes() {
	}

	public ViewIncomes(ViewIncomesId id) {
		this.id = id;
	}

	public ViewIncomesId getId() {
		return this.id;
	}

	public void setId(ViewIncomesId id) {
		this.id = id;
	}

}
