package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewPrdForInc generated by hbm2java
 */
public class ViewPrdForInc implements java.io.Serializable {

	private ViewPrdForIncId id;

	public ViewPrdForInc() {
	}

	public ViewPrdForInc(ViewPrdForIncId id) {
		this.id = id;
	}

	public ViewPrdForIncId getId() {
		return this.id;
	}

	public void setId(ViewPrdForIncId id) {
		this.id = id;
	}

}
