package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewWaybills generated by hbm2java
 */
public class ViewWaybills implements java.io.Serializable {

	private ViewWaybillsId id;

	public ViewWaybills() {
	}

	public ViewWaybills(ViewWaybillsId id) {
		this.id = id;
	}

	public ViewWaybillsId getId() {
		return this.id;
	}

	public void setId(ViewWaybillsId id) {
		this.id = id;
	}

}
