package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewRegistrInvoces generated by hbm2java
 */
public class ViewRegistrInvoces implements java.io.Serializable {

	private ViewRegistrInvocesId id;

	public ViewRegistrInvoces() {
	}

	public ViewRegistrInvoces(ViewRegistrInvocesId id) {
		this.id = id;
	}

	public ViewRegistrInvocesId getId() {
		return this.id;
	}

	public void setId(ViewRegistrInvocesId id) {
		this.id = id;
	}

}
