package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewMargin generated by hbm2java
 */
public class ViewMargin implements java.io.Serializable {

	private ViewMarginId id;

	public ViewMargin() {
	}

	public ViewMargin(ViewMarginId id) {
		this.id = id;
	}

	public ViewMarginId getId() {
		return this.id;
	}

	public void setId(ViewMarginId id) {
		this.id = id;
	}

}
