package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewCustForIns generated by hbm2java
 */
public class ViewCustForIns implements java.io.Serializable {

	private ViewCustForInsId id;

	public ViewCustForIns() {
	}

	public ViewCustForIns(ViewCustForInsId id) {
		this.id = id;
	}

	public ViewCustForInsId getId() {
		return this.id;
	}

	public void setId(ViewCustForInsId id) {
		this.id = id;
	}

}
