package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewCustomers generated by hbm2java
 */
public class ViewCustomers implements java.io.Serializable {

	private ViewCustomersId id;

	public ViewCustomers() {
	}

	public ViewCustomers(ViewCustomersId id) {
		this.id = id;
	}

	public ViewCustomersId getId() {
		return this.id;
	}

	public void setId(ViewCustomersId id) {
		this.id = id;
	}

}
