package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * ViewRegistrIncomesId generated by hbm2java
 */
public class ViewRegistrIncomesId implements java.io.Serializable {

	private int branchId;
	private int incId;
	private Timestamp incomeDate;
	private Serializable measure;
	private Serializable name;
	private int numParty;
	private int productId;
	private Double qty;

	public ViewRegistrIncomesId() {
	}

	public ViewRegistrIncomesId(int branchId, int incId, Timestamp incomeDate, Serializable measure, Serializable name,
			int numParty, int productId, Double qty) {
		this.branchId = branchId;
		this.incId = incId;
		this.incomeDate = incomeDate;
		this.measure = measure;
		this.name = name;
		this.numParty = numParty;
		this.productId = productId;
		this.qty = qty;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public int getIncId() {
		return this.incId;
	}

	public void setIncId(int incId) {
		this.incId = incId;
	}

	public Timestamp getIncomeDate() {
		return this.incomeDate;
	}

	public void setIncomeDate(Timestamp incomeDate) {
		this.incomeDate = incomeDate;
	}

	public Serializable getMeasure() {
		return this.measure;
	}

	public void setMeasure(Serializable measure) {
		this.measure = measure;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public int getNumParty() {
		return this.numParty;
	}

	public void setNumParty(int numParty) {
		this.numParty = numParty;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Double getQty() {
		return this.qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewRegistrIncomesId))
			return false;
		ViewRegistrIncomesId castOther = (ViewRegistrIncomesId) other;

		return (this.getBranchId() == castOther.getBranchId()) && (this.getIncId() == castOther.getIncId())
				&& ((this.getIncomeDate() == castOther.getIncomeDate()) || (this.getIncomeDate() != null
						&& castOther.getIncomeDate() != null && this.getIncomeDate().equals(castOther.getIncomeDate())))
				&& ((this.getMeasure() == castOther.getMeasure()) || (this.getMeasure() != null
						&& castOther.getMeasure() != null && this.getMeasure().equals(castOther.getMeasure())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& (this.getNumParty() == castOther.getNumParty()) && (this.getProductId() == castOther.getProductId())
				&& ((this.getQty() == castOther.getQty()) || (this.getQty() != null && castOther.getQty() != null
						&& this.getQty().equals(castOther.getQty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBranchId();
		result = 37 * result + this.getIncId();
		result = 37 * result + (getIncomeDate() == null ? 0 : this.getIncomeDate().hashCode());
		result = 37 * result + (getMeasure() == null ? 0 : this.getMeasure().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getNumParty();
		result = 37 * result + this.getProductId();
		result = 37 * result + (getQty() == null ? 0 : this.getQty().hashCode());
		return result;
	}

}
