package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewStockOnPrd generated by hbm2java
 */
public class ViewStockOnPrd implements java.io.Serializable {

	private ViewStockOnPrdId id;

	public ViewStockOnPrd() {
	}

	public ViewStockOnPrd(ViewStockOnPrdId id) {
		this.id = id;
	}

	public ViewStockOnPrdId getId() {
		return this.id;
	}

	public void setId(ViewStockOnPrdId id) {
		this.id = id;
	}

}
