package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewStockOnParty generated by hbm2java
 */
public class ViewStockOnParty implements java.io.Serializable {

	private ViewStockOnPartyId id;

	public ViewStockOnParty() {
	}

	public ViewStockOnParty(ViewStockOnPartyId id) {
		this.id = id;
	}

	public ViewStockOnPartyId getId() {
		return this.id;
	}

	public void setId(ViewStockOnPartyId id) {
		this.id = id;
	}

}
