package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * ViewIncomeDetailsId generated by hbm2java
 */
public class ViewIncomeDetailsId implements java.io.Serializable {

	private Serializable barcode;
	private int branchId;
	private int incId;
	private Serializable measure;
	private Serializable name;
	private int numParty;
	private Serializable numSert;
	private Double priceC;
	private Double priceCallowance;
	private Boolean prod;
	private int productId;
	private Double qty;
	private Double sumPriceCr;
	private Double sumWprice;
	private Integer tax;
	private Double taxSumR;
	private Double taxSumW;
	private Double totalPriceCurR;
	private Double totalPriceCurW;
	private Double totalPriceR;
	private Double totalPriceW;
	private Double wholeSaleSurcharge;

	public ViewIncomeDetailsId() {
	}

	public ViewIncomeDetailsId(Serializable barcode, int branchId, int incId, Serializable measure, Serializable name,
			int numParty, Serializable numSert, Double priceC, Double priceCallowance, Boolean prod, int productId,
			Double qty, Double sumPriceCr, Double sumWprice, Integer tax, Double taxSumR, Double taxSumW,
			Double totalPriceCurR, Double totalPriceCurW, Double totalPriceR, Double totalPriceW,
			Double wholeSaleSurcharge) {
		this.barcode = barcode;
		this.branchId = branchId;
		this.incId = incId;
		this.measure = measure;
		this.name = name;
		this.numParty = numParty;
		this.numSert = numSert;
		this.priceC = priceC;
		this.priceCallowance = priceCallowance;
		this.prod = prod;
		this.productId = productId;
		this.qty = qty;
		this.sumPriceCr = sumPriceCr;
		this.sumWprice = sumWprice;
		this.tax = tax;
		this.taxSumR = taxSumR;
		this.taxSumW = taxSumW;
		this.totalPriceCurR = totalPriceCurR;
		this.totalPriceCurW = totalPriceCurW;
		this.totalPriceR = totalPriceR;
		this.totalPriceW = totalPriceW;
		this.wholeSaleSurcharge = wholeSaleSurcharge;
	}

	public Serializable getBarcode() {
		return this.barcode;
	}

	public void setBarcode(Serializable barcode) {
		this.barcode = barcode;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public int getIncId() {
		return this.incId;
	}

	public void setIncId(int incId) {
		this.incId = incId;
	}

	public Serializable getMeasure() {
		return this.measure;
	}

	public void setMeasure(Serializable measure) {
		this.measure = measure;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public int getNumParty() {
		return this.numParty;
	}

	public void setNumParty(int numParty) {
		this.numParty = numParty;
	}

	public Serializable getNumSert() {
		return this.numSert;
	}

	public void setNumSert(Serializable numSert) {
		this.numSert = numSert;
	}

	public Double getPriceC() {
		return this.priceC;
	}

	public void setPriceC(Double priceC) {
		this.priceC = priceC;
	}

	public Double getPriceCallowance() {
		return this.priceCallowance;
	}

	public void setPriceCallowance(Double priceCallowance) {
		this.priceCallowance = priceCallowance;
	}

	public Boolean getProd() {
		return this.prod;
	}

	public void setProd(Boolean prod) {
		this.prod = prod;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Double getQty() {
		return this.qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	public Double getSumPriceCr() {
		return this.sumPriceCr;
	}

	public void setSumPriceCr(Double sumPriceCr) {
		this.sumPriceCr = sumPriceCr;
	}

	public Double getSumWprice() {
		return this.sumWprice;
	}

	public void setSumWprice(Double sumWprice) {
		this.sumWprice = sumWprice;
	}

	public Integer getTax() {
		return this.tax;
	}

	public void setTax(Integer tax) {
		this.tax = tax;
	}

	public Double getTaxSumR() {
		return this.taxSumR;
	}

	public void setTaxSumR(Double taxSumR) {
		this.taxSumR = taxSumR;
	}

	public Double getTaxSumW() {
		return this.taxSumW;
	}

	public void setTaxSumW(Double taxSumW) {
		this.taxSumW = taxSumW;
	}

	public Double getTotalPriceCurR() {
		return this.totalPriceCurR;
	}

	public void setTotalPriceCurR(Double totalPriceCurR) {
		this.totalPriceCurR = totalPriceCurR;
	}

	public Double getTotalPriceCurW() {
		return this.totalPriceCurW;
	}

	public void setTotalPriceCurW(Double totalPriceCurW) {
		this.totalPriceCurW = totalPriceCurW;
	}

	public Double getTotalPriceR() {
		return this.totalPriceR;
	}

	public void setTotalPriceR(Double totalPriceR) {
		this.totalPriceR = totalPriceR;
	}

	public Double getTotalPriceW() {
		return this.totalPriceW;
	}

	public void setTotalPriceW(Double totalPriceW) {
		this.totalPriceW = totalPriceW;
	}

	public Double getWholeSaleSurcharge() {
		return this.wholeSaleSurcharge;
	}

	public void setWholeSaleSurcharge(Double wholeSaleSurcharge) {
		this.wholeSaleSurcharge = wholeSaleSurcharge;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewIncomeDetailsId))
			return false;
		ViewIncomeDetailsId castOther = (ViewIncomeDetailsId) other;

		return ((this.getBarcode() == castOther.getBarcode()) || (this.getBarcode() != null
				&& castOther.getBarcode() != null && this.getBarcode().equals(castOther.getBarcode())))
				&& (this.getBranchId() == castOther.getBranchId()) && (this.getIncId() == castOther.getIncId())
				&& ((this.getMeasure() == castOther.getMeasure()) || (this.getMeasure() != null
						&& castOther.getMeasure() != null && this.getMeasure().equals(castOther.getMeasure())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& (this.getNumParty() == castOther.getNumParty())
				&& ((this.getNumSert() == castOther.getNumSert()) || (this.getNumSert() != null
						&& castOther.getNumSert() != null && this.getNumSert().equals(castOther.getNumSert())))
				&& ((this.getPriceC() == castOther.getPriceC()) || (this.getPriceC() != null
						&& castOther.getPriceC() != null && this.getPriceC().equals(castOther.getPriceC())))
				&& ((this.getPriceCallowance() == castOther.getPriceCallowance())
						|| (this.getPriceCallowance() != null && castOther.getPriceCallowance() != null
								&& this.getPriceCallowance().equals(castOther.getPriceCallowance())))
				&& ((this.getProd() == castOther.getProd()) || (this.getProd() != null && castOther.getProd() != null
						&& this.getProd().equals(castOther.getProd())))
				&& (this.getProductId() == castOther.getProductId())
				&& ((this.getQty() == castOther.getQty()) || (this.getQty() != null && castOther.getQty() != null
						&& this.getQty().equals(castOther.getQty())))
				&& ((this.getSumPriceCr() == castOther.getSumPriceCr()) || (this.getSumPriceCr() != null
						&& castOther.getSumPriceCr() != null && this.getSumPriceCr().equals(castOther.getSumPriceCr())))
				&& ((this.getSumWprice() == castOther.getSumWprice()) || (this.getSumWprice() != null
						&& castOther.getSumWprice() != null && this.getSumWprice().equals(castOther.getSumWprice())))
				&& ((this.getTax() == castOther.getTax()) || (this.getTax() != null && castOther.getTax() != null
						&& this.getTax().equals(castOther.getTax())))
				&& ((this.getTaxSumR() == castOther.getTaxSumR()) || (this.getTaxSumR() != null
						&& castOther.getTaxSumR() != null && this.getTaxSumR().equals(castOther.getTaxSumR())))
				&& ((this.getTaxSumW() == castOther.getTaxSumW()) || (this.getTaxSumW() != null
						&& castOther.getTaxSumW() != null && this.getTaxSumW().equals(castOther.getTaxSumW())))
				&& ((this.getTotalPriceCurR() == castOther.getTotalPriceCurR())
						|| (this.getTotalPriceCurR() != null && castOther.getTotalPriceCurR() != null
								&& this.getTotalPriceCurR().equals(castOther.getTotalPriceCurR())))
				&& ((this.getTotalPriceCurW() == castOther.getTotalPriceCurW())
						|| (this.getTotalPriceCurW() != null && castOther.getTotalPriceCurW() != null
								&& this.getTotalPriceCurW().equals(castOther.getTotalPriceCurW())))
				&& ((this.getTotalPriceR() == castOther.getTotalPriceR())
						|| (this.getTotalPriceR() != null && castOther.getTotalPriceR() != null
								&& this.getTotalPriceR().equals(castOther.getTotalPriceR())))
				&& ((this.getTotalPriceW() == castOther.getTotalPriceW())
						|| (this.getTotalPriceW() != null && castOther.getTotalPriceW() != null
								&& this.getTotalPriceW().equals(castOther.getTotalPriceW())))
				&& ((this.getWholeSaleSurcharge() == castOther.getWholeSaleSurcharge())
						|| (this.getWholeSaleSurcharge() != null && castOther.getWholeSaleSurcharge() != null
								&& this.getWholeSaleSurcharge().equals(castOther.getWholeSaleSurcharge())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBarcode() == null ? 0 : this.getBarcode().hashCode());
		result = 37 * result + this.getBranchId();
		result = 37 * result + this.getIncId();
		result = 37 * result + (getMeasure() == null ? 0 : this.getMeasure().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getNumParty();
		result = 37 * result + (getNumSert() == null ? 0 : this.getNumSert().hashCode());
		result = 37 * result + (getPriceC() == null ? 0 : this.getPriceC().hashCode());
		result = 37 * result + (getPriceCallowance() == null ? 0 : this.getPriceCallowance().hashCode());
		result = 37 * result + (getProd() == null ? 0 : this.getProd().hashCode());
		result = 37 * result + this.getProductId();
		result = 37 * result + (getQty() == null ? 0 : this.getQty().hashCode());
		result = 37 * result + (getSumPriceCr() == null ? 0 : this.getSumPriceCr().hashCode());
		result = 37 * result + (getSumWprice() == null ? 0 : this.getSumWprice().hashCode());
		result = 37 * result + (getTax() == null ? 0 : this.getTax().hashCode());
		result = 37 * result + (getTaxSumR() == null ? 0 : this.getTaxSumR().hashCode());
		result = 37 * result + (getTaxSumW() == null ? 0 : this.getTaxSumW().hashCode());
		result = 37 * result + (getTotalPriceCurR() == null ? 0 : this.getTotalPriceCurR().hashCode());
		result = 37 * result + (getTotalPriceCurW() == null ? 0 : this.getTotalPriceCurW().hashCode());
		result = 37 * result + (getTotalPriceR() == null ? 0 : this.getTotalPriceR().hashCode());
		result = 37 * result + (getTotalPriceW() == null ? 0 : this.getTotalPriceW().hashCode());
		result = 37 * result + (getWholeSaleSurcharge() == null ? 0 : this.getWholeSaleSurcharge().hashCode());
		return result;
	}

}
