package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewInvoices generated by hbm2java
 */
public class ViewInvoices implements java.io.Serializable {

	private ViewInvoicesId id;

	public ViewInvoices() {
	}

	public ViewInvoices(ViewInvoicesId id) {
		this.id = id;
	}

	public ViewInvoicesId getId() {
		return this.id;
	}

	public void setId(ViewInvoicesId id) {
		this.id = id;
	}

}
