package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * ViewGenrePrdId generated by hbm2java
 */
public class ViewGenrePrdId implements java.io.Serializable {

	private int branchId;
	private Serializable description;
	private int genreId;
	private Serializable name;
	private Serializable prdName;
	private int productId;
	private int uid;

	public ViewGenrePrdId() {
	}

	public ViewGenrePrdId(int branchId, Serializable description, int genreId, Serializable name, Serializable prdName,
			int productId, int uid) {
		this.branchId = branchId;
		this.description = description;
		this.genreId = genreId;
		this.name = name;
		this.prdName = prdName;
		this.productId = productId;
		this.uid = uid;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public int getGenreId() {
		return this.genreId;
	}

	public void setGenreId(int genreId) {
		this.genreId = genreId;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Serializable getPrdName() {
		return this.prdName;
	}

	public void setPrdName(Serializable prdName) {
		this.prdName = prdName;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewGenrePrdId))
			return false;
		ViewGenrePrdId castOther = (ViewGenrePrdId) other;

		return (this.getBranchId() == castOther.getBranchId())
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& (this.getGenreId() == castOther.getGenreId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getPrdName() == castOther.getPrdName()) || (this.getPrdName() != null
						&& castOther.getPrdName() != null && this.getPrdName().equals(castOther.getPrdName())))
				&& (this.getProductId() == castOther.getProductId()) && (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBranchId();
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + this.getGenreId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getPrdName() == null ? 0 : this.getPrdName().hashCode());
		result = 37 * result + this.getProductId();
		result = 37 * result + this.getUid();
		return result;
	}

}
