package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewRegistrWaybills generated by hbm2java
 */
public class ViewRegistrWaybills implements java.io.Serializable {

	private ViewRegistrWaybillsId id;

	public ViewRegistrWaybills() {
	}

	public ViewRegistrWaybills(ViewRegistrWaybillsId id) {
		this.id = id;
	}

	public ViewRegistrWaybillsId getId() {
		return this.id;
	}

	public void setId(ViewRegistrWaybillsId id) {
		this.id = id;
	}

}
