package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;

/**
 * ViewOrderDetailsId generated by hbm2java
 */
public class ViewOrderDetailsId implements java.io.Serializable {

	private Serializable bar;
	private int branchId;
	private Serializable measure;
	private Serializable name;
	private int ordId;
	private int productId;
	private Double qty;
	private int uid;

	public ViewOrderDetailsId() {
	}

	public ViewOrderDetailsId(Serializable bar, int branchId, Serializable measure, Serializable name, int ordId,
			int productId, Double qty, int uid) {
		this.bar = bar;
		this.branchId = branchId;
		this.measure = measure;
		this.name = name;
		this.ordId = ordId;
		this.productId = productId;
		this.qty = qty;
		this.uid = uid;
	}

	public Serializable getBar() {
		return this.bar;
	}

	public void setBar(Serializable bar) {
		this.bar = bar;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public Serializable getMeasure() {
		return this.measure;
	}

	public void setMeasure(Serializable measure) {
		this.measure = measure;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public int getOrdId() {
		return this.ordId;
	}

	public void setOrdId(int ordId) {
		this.ordId = ordId;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Double getQty() {
		return this.qty;
	}

	public void setQty(Double qty) {
		this.qty = qty;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewOrderDetailsId))
			return false;
		ViewOrderDetailsId castOther = (ViewOrderDetailsId) other;

		return ((this.getBar() == castOther.getBar())
				|| (this.getBar() != null && castOther.getBar() != null && this.getBar().equals(castOther.getBar())))
				&& (this.getBranchId() == castOther.getBranchId())
				&& ((this.getMeasure() == castOther.getMeasure()) || (this.getMeasure() != null
						&& castOther.getMeasure() != null && this.getMeasure().equals(castOther.getMeasure())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& (this.getOrdId() == castOther.getOrdId()) && (this.getProductId() == castOther.getProductId())
				&& ((this.getQty() == castOther.getQty()) || (this.getQty() != null && castOther.getQty() != null
						&& this.getQty().equals(castOther.getQty())))
				&& (this.getUid() == castOther.getUid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBar() == null ? 0 : this.getBar().hashCode());
		result = 37 * result + this.getBranchId();
		result = 37 * result + (getMeasure() == null ? 0 : this.getMeasure().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getOrdId();
		result = 37 * result + this.getProductId();
		result = 37 * result + (getQty() == null ? 0 : this.getQty().hashCode());
		result = 37 * result + this.getUid();
		return result;
	}

}
