package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * ViewPrdForInvWblId generated by hbm2java
 */
public class ViewPrdForInvWblId implements java.io.Serializable {

	private int branchId;
	private Serializable country;
	private Serializable description;
	private Timestamp incomeDate;
	private Serializable measure;
	private Serializable name;
	private int numParty;
	private int productId;
	private Integer qty;
	private Double qtyAll;
	private Double qtyInv;
	private Double qtyStock;
	private Integer tax;
	private Double taxSumR;
	private Double taxSumW;

	public ViewPrdForInvWblId() {
	}

	public ViewPrdForInvWblId(int branchId, Serializable country, Serializable description, Timestamp incomeDate,
			Serializable measure, Serializable name, int numParty, int productId, Integer qty, Double qtyAll,
			Double qtyInv, Double qtyStock, Integer tax, Double taxSumR, Double taxSumW) {
		this.branchId = branchId;
		this.country = country;
		this.description = description;
		this.incomeDate = incomeDate;
		this.measure = measure;
		this.name = name;
		this.numParty = numParty;
		this.productId = productId;
		this.qty = qty;
		this.qtyAll = qtyAll;
		this.qtyInv = qtyInv;
		this.qtyStock = qtyStock;
		this.tax = tax;
		this.taxSumR = taxSumR;
		this.taxSumW = taxSumW;
	}

	public int getBranchId() {
		return this.branchId;
	}

	public void setBranchId(int branchId) {
		this.branchId = branchId;
	}

	public Serializable getCountry() {
		return this.country;
	}

	public void setCountry(Serializable country) {
		this.country = country;
	}

	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	public Timestamp getIncomeDate() {
		return this.incomeDate;
	}

	public void setIncomeDate(Timestamp incomeDate) {
		this.incomeDate = incomeDate;
	}

	public Serializable getMeasure() {
		return this.measure;
	}

	public void setMeasure(Serializable measure) {
		this.measure = measure;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public int getNumParty() {
		return this.numParty;
	}

	public void setNumParty(int numParty) {
		this.numParty = numParty;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	public Double getQtyAll() {
		return this.qtyAll;
	}

	public void setQtyAll(Double qtyAll) {
		this.qtyAll = qtyAll;
	}

	public Double getQtyInv() {
		return this.qtyInv;
	}

	public void setQtyInv(Double qtyInv) {
		this.qtyInv = qtyInv;
	}

	public Double getQtyStock() {
		return this.qtyStock;
	}

	public void setQtyStock(Double qtyStock) {
		this.qtyStock = qtyStock;
	}

	public Integer getTax() {
		return this.tax;
	}

	public void setTax(Integer tax) {
		this.tax = tax;
	}

	public Double getTaxSumR() {
		return this.taxSumR;
	}

	public void setTaxSumR(Double taxSumR) {
		this.taxSumR = taxSumR;
	}

	public Double getTaxSumW() {
		return this.taxSumW;
	}

	public void setTaxSumW(Double taxSumW) {
		this.taxSumW = taxSumW;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewPrdForInvWblId))
			return false;
		ViewPrdForInvWblId castOther = (ViewPrdForInvWblId) other;

		return (this.getBranchId() == castOther.getBranchId())
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& ((this.getIncomeDate() == castOther.getIncomeDate()) || (this.getIncomeDate() != null
						&& castOther.getIncomeDate() != null && this.getIncomeDate().equals(castOther.getIncomeDate())))
				&& ((this.getMeasure() == castOther.getMeasure()) || (this.getMeasure() != null
						&& castOther.getMeasure() != null && this.getMeasure().equals(castOther.getMeasure())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& (this.getNumParty() == castOther.getNumParty()) && (this.getProductId() == castOther.getProductId())
				&& ((this.getQty() == castOther.getQty()) || (this.getQty() != null && castOther.getQty() != null
						&& this.getQty().equals(castOther.getQty())))
				&& ((this.getQtyAll() == castOther.getQtyAll()) || (this.getQtyAll() != null
						&& castOther.getQtyAll() != null && this.getQtyAll().equals(castOther.getQtyAll())))
				&& ((this.getQtyInv() == castOther.getQtyInv()) || (this.getQtyInv() != null
						&& castOther.getQtyInv() != null && this.getQtyInv().equals(castOther.getQtyInv())))
				&& ((this.getQtyStock() == castOther.getQtyStock()) || (this.getQtyStock() != null
						&& castOther.getQtyStock() != null && this.getQtyStock().equals(castOther.getQtyStock())))
				&& ((this.getTax() == castOther.getTax()) || (this.getTax() != null && castOther.getTax() != null
						&& this.getTax().equals(castOther.getTax())))
				&& ((this.getTaxSumR() == castOther.getTaxSumR()) || (this.getTaxSumR() != null
						&& castOther.getTaxSumR() != null && this.getTaxSumR().equals(castOther.getTaxSumR())))
				&& ((this.getTaxSumW() == castOther.getTaxSumW()) || (this.getTaxSumW() != null
						&& castOther.getTaxSumW() != null && this.getTaxSumW().equals(castOther.getTaxSumW())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBranchId();
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + (getIncomeDate() == null ? 0 : this.getIncomeDate().hashCode());
		result = 37 * result + (getMeasure() == null ? 0 : this.getMeasure().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getNumParty();
		result = 37 * result + this.getProductId();
		result = 37 * result + (getQty() == null ? 0 : this.getQty().hashCode());
		result = 37 * result + (getQtyAll() == null ? 0 : this.getQtyAll().hashCode());
		result = 37 * result + (getQtyInv() == null ? 0 : this.getQtyInv().hashCode());
		result = 37 * result + (getQtyStock() == null ? 0 : this.getQtyStock().hashCode());
		result = 37 * result + (getTax() == null ? 0 : this.getTax().hashCode());
		result = 37 * result + (getTaxSumR() == null ? 0 : this.getTaxSumR().hashCode());
		result = 37 * result + (getTaxSumW() == null ? 0 : this.getTaxSumW().hashCode());
		return result;
	}

}
