package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewInvoceDetails generated by hbm2java
 */
public class ViewInvoceDetails implements java.io.Serializable {

	private ViewInvoceDetailsId id;

	public ViewInvoceDetails() {
	}

	public ViewInvoceDetails(ViewInvoceDetailsId id) {
		this.id = id;
	}

	public ViewInvoceDetailsId getId() {
		return this.id;
	}

	public void setId(ViewInvoceDetailsId id) {
		this.id = id;
	}

}
