package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewGenrePrd generated by hbm2java
 */
public class ViewGenrePrd implements java.io.Serializable {

	private ViewGenrePrdId id;

	public ViewGenrePrd() {
	}

	public ViewGenrePrd(ViewGenrePrdId id) {
		this.id = id;
	}

	public ViewGenrePrdId getId() {
		return this.id;
	}

	public void setId(ViewGenrePrdId id) {
		this.id = id;
	}

}
