package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewOrders generated by hbm2java
 */
public class ViewOrders implements java.io.Serializable {

	private ViewOrdersId id;

	public ViewOrders() {
	}

	public ViewOrders(ViewOrdersId id) {
		this.id = id;
	}

	public ViewOrdersId getId() {
		return this.id;
	}

	public void setId(ViewOrdersId id) {
		this.id = id;
	}

}
