package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewWaybillDetails generated by hbm2java
 */
public class ViewWaybillDetails implements java.io.Serializable {

	private ViewWaybillDetailsId id;

	public ViewWaybillDetails() {
	}

	public ViewWaybillDetails(ViewWaybillDetailsId id) {
		this.id = id;
	}

	public ViewWaybillDetailsId getId() {
		return this.id;
	}

	public void setId(ViewWaybillDetailsId id) {
		this.id = id;
	}

}
