package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewPrdForInvWbl generated by hbm2java
 */
public class ViewPrdForInvWbl implements java.io.Serializable {

	private ViewPrdForInvWblId id;

	public ViewPrdForInvWbl() {
	}

	public ViewPrdForInvWbl(ViewPrdForInvWblId id) {
		this.id = id;
	}

	public ViewPrdForInvWblId getId() {
		return this.id;
	}

	public void setId(ViewPrdForInvWblId id) {
		this.id = id;
	}

}
