package com.entity;
// Generated 28 янв. 2024 г., 15:09:29 by Hibernate Tools 6.3.1.Final

/**
 * ViewRegistrIncomes generated by hbm2java
 */
public class ViewRegistrIncomes implements java.io.Serializable {

	private ViewRegistrIncomesId id;

	public ViewRegistrIncomes() {
	}

	public ViewRegistrIncomes(ViewRegistrIncomesId id) {
		this.id = id;
	}

	public ViewRegistrIncomesId getId() {
		return this.id;
	}

	public void setId(ViewRegistrIncomesId id) {
		this.id = id;
	}

}
